import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const sourcePath = path.join(packageRoot, "src", "resume.types.ts");
const outputPath = path.join(packageRoot, "src", "str.ts");

const sourceText = await fs.readFile(sourcePath, "utf8");
const sourceFile = ts.createSourceFile(
	sourcePath,
	sourceText,
	ts.ScriptTarget.Latest,
	true,
	ts.ScriptKind.TS,
);

const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
const typeStatements = sourceFile.statements.filter((statement) =>
	ts.isTypeAliasDeclaration(statement) ||
	ts.isInterfaceDeclaration(statement) ||
	ts.isEnumDeclaration(statement),
);

if (typeStatements.length === 0) {
	throw new Error(`Could not find any type declarations in ${sourcePath}`);
}

const resumeTypeSource = typeStatements
	.map((statement) =>
		printer.printNode(ts.EmitHint.Unspecified, statement, sourceFile),
	)
	.join("\n\n");

const output = [
	"// This file is generated by scripts/generate-str.mjs.",
	"// Do not edit by hand.",
	"",
	`export const RESUME_TYPES = ${JSON.stringify(resumeTypeSource)} as const;`,
	`export const RESUME_TYPE = RESUME_TYPES;`,
	"",
].join("\n");

await fs.writeFile(outputPath, output, "utf8");

console.log(`Wrote ${path.relative(packageRoot, outputPath)}`);
